# Generated by Django 2.2.7 on 2019-12-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191207_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('', '----'), ('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10),
        ),
    ]
