# Generated by Django 2.2.7 on 2019-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191207_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('', '----'), ('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], default='', max_length=10),
        ),
    ]
