# Generated by Django 2.2.7 on 2019-12-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191207_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('', '----'), ('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], max_length=10),
        ),
    ]
